apiVersion: k8s.nginx.org/v1
kind: Policy
metadata:
  name: waf-policy
spec:
  waf:
    enable: true
    apPolicy: "default/dataguard-block"
    securityLog:
      enable: true
      apLogConf: "default/logconf"
      #logDest: "syslog:server=syslog-svc-2.default.svc.cluster.local:514"
      logDest: "syslog:server=10.1.10.7:5144"
